version: '3.8'  

services:
  credutpay:
    container_name: CredutPayContainer
    build:
      context: ./WebApi   
      dockerfile: Dockerfile  
    image: webapi
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=credutpaydb;Username=postgres;Password=postgres

  postgres:
    image: postgres:16
    container_name: credutpay_postgres
    environment:
      POSTGRES_DB: credutpaydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
